"""empty message

Revision ID: 904ba16c7804
Revises: b261cbc09189
Create Date: 2024-10-25 23:49:47.499038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904ba16c7804'
down_revision = 'b261cbc09189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_editorial_id', type_='foreignkey')
        batch_op.drop_constraint('fk_books_genre_id', type_='foreignkey')
        batch_op.drop_constraint('fk_books_author_id', type_='foreignkey')
        batch_op.drop_column('genre_id')
        batch_op.drop_column('editorial_id')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('editorial_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('genre_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_books_author_id', 'authors', ['author_id'], ['id'])
        batch_op.create_foreign_key('fk_books_genre_id', 'genres', ['genre_id'], ['id'])
        batch_op.create_foreign_key('fk_books_editorial_id', 'editorial', ['editorial_id'], ['id'])

    # ### end Alembic commands ###
