"""empty message

Revision ID: b261cbc09189
Revises: 84d70e43a20d
Create Date: 2024-10-23 00:16:37.746033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b261cbc09189'
down_revision = '84d70e43a20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('editorial_id', sa.Integer(), nullable=False))
        
        # Added names for foreign key constraints
        batch_op.create_foreign_key('fk_books_genre_id', 'genres', ['genre_id'], ['id'])
        batch_op.create_foreign_key('fk_books_author_id', 'authors', ['author_id'], ['id'])
        batch_op.create_foreign_key('fk_books_editorial_id', 'editorial', ['editorial_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        # Added names for dropping constraints
        batch_op.drop_constraint('fk_books_genre_id', type_='foreignkey')
        batch_op.drop_constraint('fk_books_author_id', type_='foreignkey')
        batch_op.drop_constraint('fk_books_editorial_id', type_='foreignkey')
        
        batch_op.drop_column('editorial_id')
        batch_op.drop_column('author_id')
        batch_op.drop_column('genre_id')

    # ### end Alembic commands ###
