"""empty message

Revision ID: bb58ca8c3a08
Revises: 04cdf7febe06
Create Date: 2024-10-22 23:38:38.424816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb58ca8c3a08'
down_revision = '04cdf7febe06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=120), nullable=True))

    op.drop_table('editorial')
    # ### end Alembic commands ###
